//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"
	fmt "fmt"

	equality "k8s.io/apimachinery/pkg/api/equality"
	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	runtime "k8s.io/apimachinery/pkg/runtime"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *runtime.Scheme) error {
	// type ClusterRoleBinding
	scheme.AddValidationFunc((*ClusterRoleBinding)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_ClusterRoleBinding(ctx, op, nil /* fldPath */, obj.(*ClusterRoleBinding), safe.Cast[*ClusterRoleBinding](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	// type ClusterRoleBindingList
	scheme.AddValidationFunc((*ClusterRoleBindingList)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_ClusterRoleBindingList(ctx, op, nil /* fldPath */, obj.(*ClusterRoleBindingList), safe.Cast[*ClusterRoleBindingList](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	// type RoleBinding
	scheme.AddValidationFunc((*RoleBinding)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_RoleBinding(ctx, op, nil /* fldPath */, obj.(*RoleBinding), safe.Cast[*RoleBinding](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	// type RoleBindingList
	scheme.AddValidationFunc((*RoleBindingList)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_RoleBindingList(ctx, op, nil /* fldPath */, obj.(*RoleBindingList), safe.Cast[*RoleBindingList](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	return nil
}

// Validate_ClusterRoleBinding validates an instance of ClusterRoleBinding according
// to declarative validation rules in the API schema.
func Validate_ClusterRoleBinding(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ClusterRoleBinding) (errs field.ErrorList) {
	// field ClusterRoleBinding.TypeMeta has no validation
	// field ClusterRoleBinding.ObjectMeta has no validation

	// field ClusterRoleBinding.Subjects
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj []Subject, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil
			}
			// iterate the list and call the type's validation function
			errs = append(errs, validate.EachSliceVal(ctx, op, fldPath, obj, oldObj, nil, nil, Validate_Subject)...)
			return
		}(fldPath.Child("subjects"), obj.Subjects, safe.Field(oldObj, func(oldObj *ClusterRoleBinding) []Subject { return oldObj.Subjects }), oldObj != nil)...)

	// field ClusterRoleBinding.RoleRef
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *RoleRef, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil
			}
			// call the type's validation function
			errs = append(errs, Validate_RoleRef(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("roleRef"), &obj.RoleRef, safe.Field(oldObj, func(oldObj *ClusterRoleBinding) *RoleRef { return &oldObj.RoleRef }), oldObj != nil)...)

	return errs
}

// Validate_ClusterRoleBindingList validates an instance of ClusterRoleBindingList according
// to declarative validation rules in the API schema.
func Validate_ClusterRoleBindingList(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *ClusterRoleBindingList) (errs field.ErrorList) {
	// field ClusterRoleBindingList.TypeMeta has no validation
	// field ClusterRoleBindingList.ListMeta has no validation

	// field ClusterRoleBindingList.Items
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj []ClusterRoleBinding, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil
			}
			// iterate the list and call the type's validation function
			errs = append(errs, validate.EachSliceVal(ctx, op, fldPath, obj, oldObj, nil, nil, Validate_ClusterRoleBinding)...)
			return
		}(fldPath.Child("items"), obj.Items, safe.Field(oldObj, func(oldObj *ClusterRoleBindingList) []ClusterRoleBinding { return oldObj.Items }), oldObj != nil)...)

	return errs
}

// Validate_RoleBinding validates an instance of RoleBinding according
// to declarative validation rules in the API schema.
func Validate_RoleBinding(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *RoleBinding) (errs field.ErrorList) {
	// field RoleBinding.TypeMeta has no validation
	// field RoleBinding.ObjectMeta has no validation

	// field RoleBinding.Subjects
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj []Subject, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil
			}
			// iterate the list and call the type's validation function
			errs = append(errs, validate.EachSliceVal(ctx, op, fldPath, obj, oldObj, nil, nil, Validate_Subject)...)
			return
		}(fldPath.Child("subjects"), obj.Subjects, safe.Field(oldObj, func(oldObj *RoleBinding) []Subject { return oldObj.Subjects }), oldObj != nil)...)

	// field RoleBinding.RoleRef
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *RoleRef, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil
			}
			// call the type's validation function
			errs = append(errs, Validate_RoleRef(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("roleRef"), &obj.RoleRef, safe.Field(oldObj, func(oldObj *RoleBinding) *RoleRef { return &oldObj.RoleRef }), oldObj != nil)...)

	return errs
}

// Validate_RoleBindingList validates an instance of RoleBindingList according
// to declarative validation rules in the API schema.
func Validate_RoleBindingList(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *RoleBindingList) (errs field.ErrorList) {
	// field RoleBindingList.TypeMeta has no validation
	// field RoleBindingList.ListMeta has no validation

	// field RoleBindingList.Items
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj []RoleBinding, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && equality.Semantic.DeepEqual(obj, oldObj) {
				return nil
			}
			// iterate the list and call the type's validation function
			errs = append(errs, validate.EachSliceVal(ctx, op, fldPath, obj, oldObj, nil, nil, Validate_RoleBinding)...)
			return
		}(fldPath.Child("items"), obj.Items, safe.Field(oldObj, func(oldObj *RoleBindingList) []RoleBinding { return oldObj.Items }), oldObj != nil)...)

	return errs
}

// Validate_RoleRef validates an instance of RoleRef according
// to declarative validation rules in the API schema.
func Validate_RoleRef(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *RoleRef) (errs field.ErrorList) {
	// field RoleRef.APIGroup has no validation
	// field RoleRef.Kind has no validation

	// field RoleRef.Name
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			return
		}(fldPath.Child("name"), &obj.Name, safe.Field(oldObj, func(oldObj *RoleRef) *string { return &oldObj.Name }), oldObj != nil)...)

	return errs
}

// Validate_Subject validates an instance of Subject according
// to declarative validation rules in the API schema.
func Validate_Subject(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *Subject) (errs field.ErrorList) {
	// field Subject.Kind has no validation
	// field Subject.APIVersion has no validation

	// field Subject.Name
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil
			}
			// call field-attached validations
			earlyReturn := false
			if e := validate.RequiredValue(ctx, op, fldPath, obj, oldObj); len(e) != 0 {
				errs = append(errs, e...)
				earlyReturn = true
			}
			if earlyReturn {
				return // do not proceed
			}
			return
		}(fldPath.Child("name"), &obj.Name, safe.Field(oldObj, func(oldObj *Subject) *string { return &oldObj.Name }), oldObj != nil)...)

	// field Subject.Namespace has no validation
	return errs
}
