//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by validation-gen. DO NOT EDIT.

package v1

import (
	context "context"
	fmt "fmt"

	operation "k8s.io/apimachinery/pkg/api/operation"
	safe "k8s.io/apimachinery/pkg/api/safe"
	validate "k8s.io/apimachinery/pkg/api/validate"
	runtime "k8s.io/apimachinery/pkg/runtime"
	field "k8s.io/apimachinery/pkg/util/validation/field"
)

func init() { localSchemeBuilder.Register(RegisterValidations) }

// RegisterValidations adds validation functions to the given scheme.
// Public to allow building arbitrary schemes.
func RegisterValidations(scheme *runtime.Scheme) error {
	// type Event
	scheme.AddValidationFunc((*Event)(nil), func(ctx context.Context, op operation.Operation, obj, oldObj interface{}) field.ErrorList {
		switch op.Request.SubresourcePath() {
		case "/":
			return Validate_Event(ctx, op, nil /* fldPath */, obj.(*Event), safe.Cast[*Event](oldObj))
		}
		return field.ErrorList{field.InternalError(nil, fmt.Errorf("no validation found for %T, subresource: %v", obj, op.Request.SubresourcePath()))}
	})
	return nil
}

// Validate_Event validates an instance of Event according
// to declarative validation rules in the API schema.
func Validate_Event(ctx context.Context, op operation.Operation, fldPath *field.Path, obj, oldObj *Event) (errs field.ErrorList) {
	// field Event.TypeMeta has no validation
	// field Event.ObjectMeta has no validation
	// field Event.EventTime has no validation
	// field Event.Series has no validation

	// field Event.ReportingController
	errs = append(errs,
		func(fldPath *field.Path, obj, oldObj *string, oldValueCorrelated bool) (errs field.ErrorList) {
			// don't revalidate unchanged data
			if oldValueCorrelated && op.Type == operation.Update && (obj == oldObj || (obj != nil && oldObj != nil && *obj == *oldObj)) {
				return nil
			}
			// call field-attached validations
			errs = append(errs, validate.LabelKey(ctx, op, fldPath, obj, oldObj)...)
			return
		}(fldPath.Child("reportingController"), &obj.ReportingController, safe.Field(oldObj, func(oldObj *Event) *string { return &oldObj.ReportingController }), oldObj != nil)...)

	// field Event.ReportingInstance has no validation
	// field Event.Action has no validation
	// field Event.Reason has no validation
	// field Event.Regarding has no validation
	// field Event.Related has no validation
	// field Event.Note has no validation
	// field Event.Type has no validation
	// field Event.DeprecatedSource has no validation
	// field Event.DeprecatedFirstTimestamp has no validation
	// field Event.DeprecatedLastTimestamp has no validation
	// field Event.DeprecatedCount has no validation
	return errs
}
